version: '3'

services:
  app:
    build: .
    volumes:
      - ./:/app
      - ~/.aws:/root/.aws
    ports:
      - 8080:8080

  manager:
    build: manager
    volumes:
      - ./manager:/app
    ports:
      - 8081:8080

networks:
  intranet:
    driver: bridge